export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
//admin
export const GET_ADMIN_ERRORS = "GET_ADMIN_ERRORS";
export const ADMIN_LOADING = "ADMIN_LOADING";
export const SET_CURRENT_ADMIN = "SET_CURRENT_ADMIN";
export const SET_PLAN_WITH_CARD = "SET_PLAN_WITH_CARD";
